# Generated by Django 5.1.2 on 2024-11-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='NOME')),
                ('sobrenome', models.TextField(db_column='SOBRENOME')),
                ('distancia', models.IntegerField(db_column='DISTANCIA')),
                ('tempo', models.DurationField(max_length=20)),
            ],
            options={
                'db_table': 'runners.db',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Participante1',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='NOME')),
                ('sobrenome', models.TextField(db_column='SOBRENOME')),
                ('genero', models.TextField(db_column='GENERO')),
                ('dtNasc', models.DateField(db_column='DTNASC')),
                ('idade', models.PositiveIntegerField(db_column='IDADE')),
                ('distancia', models.TextField(db_column='DISTANCIA')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'corrida_pessoa',
                'ordering': ['user_id'],
                'managed': True,
            },
        ),
    ]
