# Generated by Django 5.1.2 on 2024-12-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participante',
            options={'managed': True, 'ordering': ['sobrenome']},
        ),
        migrations.AlterField(
            model_name='participante',
            name='distancia',
            field=models.IntegerField(choices=[(5, '5 quilômetros'), (10, '10 quilômetros'), (21, '21 quilômetros')], db_column='DISTANCIA'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tempo',
            field=models.TextField(db_column='TEMPO', max_length=20),
        ),
    ]
