# Generated by Django 5.1.2 on 2024-12-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0003_alter_participante_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participante',
            table='runners.db',
        ),
    ]
